import { useState } from 'react'

const Books = ( {books }) => {
 const filteredBooks = books.filter(book => book.genre === "Science Fiction")

 const bookListing = filteredBooks.map(book => 
  <div key = {book.id}>
      <p>Title : {book.title}</p>
      <p>Genre : {book.genre}</p>
    </div>
 )

 return(
  <>
    <h2>Books Detail</h2>
    {bookListing}
  </>
 )
}

const Users = ( {users} ) => {
  const filteredUsers = users.filter(user => user.role === "Admin")

  const userListing = filteredUsers.map(user => 
    <div key = {user.id}>
      <p>Name : {user.name}</p>
      <p>Role : {user.role}</p>
    </div>
  )

  return(
    <>
      <h2>User Details</h2>
      {userListing}
    </>
  )
}

const Products = ( {products} ) => {
  const filteredProducts = products.filter(product => product.price > 100)

  const productListing = filteredProducts.map(product => 
    <div key = {product.id}>
      <p>Name : {product.name}</p>
      <p>Price : {product.price}</p>
      <p>Features : {product.features.color}</p>
      <p>{product.features.isWaterProof ? "Water Proof" : "Not water proof"}</p>
    </div>
  )

  return(
    <>
      <h2>Products Detail</h2>
      {productListing}
    </>
  )
}

const Cities = ( {cities} ) => {
  const filteredCities = cities.filter(city => city.population > 1000000)

  const citiesListing = filteredCities.map(city => 
    <div key = {city.id}>
      <p>Name : {city.name}</p>
      <p>Population : {city.population}</p>
    </div>
  )

  return(
    <>
      <h2>Cities Detail</h2>
      {citiesListing}
    </>
  )
}

const Movies = ( {movies} ) => {
  const filteredMovies = movies.filter(movie => movie.releaseYear > 2015)

  const moviesListing = filteredMovies.map(movie => 
    <div key = {movie.id}>
      <p>Title : {movie.title}</p>
      <p>Release Year : {movie.releaseYear}</p>
    </div>
  )

  return(
    <>
      <h2>Movies Detail</h2>
      {moviesListing}
    </>
  )
}

const Podcasts = ( {podcasts} ) => {
  const filteredPodcasts = podcasts.filter(podcast => podcast.featured)

  const podcastListing = filteredPodcasts.map(podcast => 
    <div key = {podcast.id}>
      <p>Title : {podcast.title}</p>
      <p>Host : {podcast.host.join(", ")}</p>
      <p>Featured : {podcast.featured ? "Featured" : "Not Featured"}</p>
    </div>
  )

  return(
    <>
      <h2>Podcast Detail</h2>
      {podcastListing}
    </>
  )
}

const MoviesDetails = ( {moviesDetails} ) => {
  const filteredMovies = moviesDetails.filter(movie => movie.releaseYear >= 2000)

  const totalDuration = filteredMovies.reduce((acc, curr) => acc + curr.duration, 0)

  const averageDuration = totalDuration / filteredMovies.length
  return(
    <>
      <h2>Movies Details</h2>
      <p>Average Duration of Movies : {averageDuration}</p>
    </>
  )
}

const Tasks = ( {tasks} ) => {
  const totalCompletedTask = tasks.reduce((acc, curr) => curr.completed ? acc + 1 : acc, 0)
  return(
    <>
      <h2>Total Tasks Completed</h2>
      <p>Total Number : {totalCompletedTask}</p>
    </>
  )
}

const Vehicles = ( {vehicles} ) => {
  const totalDistance = vehicles.reduce((acc, curr) => acc + curr.distance, 0)

  return(
    <div>
      <h2>Vehicles Details</h2>
      <p>Total Distance Traveled : {totalDistance}</p>
    </div>
  )
}

const Sales = ( {sales} ) => {
  const totalRevenue = sales.reduce((acc, curr) => acc + curr.quantity * curr.price, 0)

  return(
    <div>
      <h2>Total Revenue Generated By all Sales Transaction</h2>
      <p>Total Revenue : {totalRevenue}</p>
    </div>
  )
}

function App() {

 const books = [

  { id: 1, title: "Dune", genre: "Science Fiction" },
  { id: 2, title: "Neuromancer", genre: "Science Fiction" },
  { id: 3, title: "Foundation", genre: "Sci-fi" }

]

const users = [

  { id: 1, name: "Alice", role: "User" },
  { id: 2, name: "Bob", role: "Admin" },
  { id: 3, name: "Charlie", role: "User" },
  { id: 4, name: "John", role: "Admin" }

]

const products = [

  { id: 1, name: "Laptop", price: 1200, features: {color: "green", isWaterProof: false} },
  { id: 2, name: "Smartphone", price: 800, features: {color: "blue", isWaterProof: true} },
  { id: 3, name: "Headphones", price: 150, features: {color: "silver", isWaterProof: false} }

]

const cities = [

  { id: 1, name: "New York", population: 8500000 },
  { id: 2, name: "Los Angeles", population: 539900 },
  { id: 3, name: "Chicago", population: 2700000 }

]

const movies = [

  { id: 1, title: "Inception", releaseYear: 2010 },
  { id: 2, title: "La La Land", releaseYear: 2016 },
  { id: 3, title: "Interstellar", releaseYear: 2014 },
  { id: 4, title: "Dune 2", releaseYear: 2024 }

]

const podcasts = [

  { id: 1, title: "Tech Talk", host: ["host 1"], featured: true },
  { id: 2, title: "Business Insights", host: ["host 2"], featured: false },
  { id: 3, title: "Science Hour", host: ["host 3", "host 4"], featured: true }

]

const moviesDetails = [

  { id: 1, title: "The Matrix", duration: 136, releaseYear: 1999 },
  { id: 2, title: "Inception", duration: 148, releaseYear: 2010 },
  { id: 3, title: "Avatar", duration: 162, releaseYear: 2009 }

]

const tasks = [

  { id: 1, description: "Complete project proposal", completed: true },
  { id: 2, description: "Review client feedback", completed: false },
  { id: 3, description: "Submit final report", completed: true }

]

const vehicles = [

  { id: 1, name: "Car", distance: 150 },
  { id: 2, name: "Bicycle", distance: 10 },
  { id: 3, name: "Motorcycle", distance: 75 }

]

const sales = [

  { id: 1, product: "Widget A", price: 25, quantity: 10 },
  { id: 2, product: "Gadget B", price: 50, quantity: 5 },
  { id: 3, product: "Tool C", price: 30, quantity: 8 }

]

  return (
    <>
      <Books books = {books}/>
      <hr/>
      <Users users = {users}/>
      <hr/>
      <Products products = {products}/>
      <hr/>
      <Cities cities = {cities}/>
      <hr/>
      <Movies movies = {movies}/>
      <hr/>
      <Podcasts podcasts = {podcasts}/>
      <hr/>
      <MoviesDetails moviesDetails = {moviesDetails}/>
      <hr/>
      <Tasks tasks = {tasks}/>
      <hr/>
      <Vehicles vehicles = {vehicles}/>
      <hr/>
      <Sales sales = {sales}/>
   </>
  )
}

export default App
